name: Secure RDP with Tailscale

on:
  workflow_dispatch: # Run manually from GitHub Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Enable Remote Desktop and disable NLA
      - name: Configure RDP
        shell: pwsh
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
          Write-Host "✅ RDP enabled."

      # Create a new RDP user with secure password
      - name: Create RDP User
        shell: pwsh
        run: |
          $username = "rdpuser"
          $password = "P@ssw0rd123!"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser $username -Password $securePassword -FullName "RDP User" -Description "User for RDP"
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Write-Host "✅ RDP user created: $username / $password"

      # Install Tailscale
      - name: Install Tailscale
        shell: pwsh
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList @("/i", "`"$installerPath`"", "/qn", "/norestart") -Wait -NoNewWindow
          if (Get-Command tailscale.exe -ErrorAction SilentlyContinue) {
              Write-Host "✅ Tailscale installed successfully."
          } else {
              Write-Host "❌ Tailscale installation failed."
              Exit 1
          }

      # Authenticate to Tailscale (replace with your AUTH KEY)
      - name: Connect Tailscale
        shell: pwsh
        run: |
          $env:kErR5Ys6eA11CNTRL = "${{ secrets.TAILSCALE_AUTH_KEY }}"
          tailscale up --authkey $env:TS_KEY --accept-routes --accept-dns=false
          tailscale ip -4
          Write-Host "✅ Connected to Tailscale network."

      - name: Keep Alive
        run: |
          echo "RDP ready! Keeping session alive..."
          sleep 3600
